import type { Metadata } from 'next';
import LegalPage, { type LegalSection } from '@/components/legal/LegalPage';
import { getCanonicalUrl } from '@/lib/seo/canonical';
import { LEGAL } from '@/lib/legal/config';

export const metadata: Metadata = {
  title: 'Terms of Service | Vizzion',
  description:
    'The terms that govern use of Vizzion — our website, customer dashboard, and embeddable visualization widget — for businesses and for people who use the widget.',
  alternates: {
    canonical: getCanonicalUrl('/terms'),
  },
  openGraph: {
    title: 'Terms of Service | Vizzion',
    description:
      'The terms that govern use of Vizzion — our website, customer dashboard, and embeddable visualization widget — for businesses and for people who use the widget.',
    url: '/terms',
  },
};

const legalEmailLink = <a href={`mailto:${LEGAL.legalEmail}`}>{LEGAL.legalEmail}</a>;
const supportEmailLink = (
  <a href={`mailto:${LEGAL.supportEmail}`}>{LEGAL.supportEmail}</a>
);
const salesEmailLink = <a href={`mailto:${LEGAL.salesEmail}`}>{LEGAL.salesEmail}</a>;

const sections: LegalSection[] = [
  {
    id: 'agreement',
    title: 'Agreement to these Terms',
    body: (
      <>
        <p>
          These Terms of Service (the “Terms”) are a binding agreement between you
          and {LEGAL.legalEntityName} (“Vizzion,” “we,” “us,” or “our”) and govern
          your use of our websites at{' '}
          <a href={LEGAL.siteUrl}>{LEGAL.siteDomain}</a> and{' '}
          <a href={LEGAL.appUrl}>app.{LEGAL.siteDomain}</a>, our customer
          dashboard, the embeddable visualization widget, and related services
          (together, the “Service”).
        </p>
        <p>
          By accessing or using the Service — including by embedding the widget,
          creating an account, or uploading a photo through a widget — you agree
          to these Terms and to our{' '}
          <a href={LEGAL.siteUrl + '/privacy'}>Privacy Policy</a>. If you do not
          agree, do not use the Service. If you use the Service on behalf of a
          business, you represent that you are authorized to bind that business,
          and “you” refers to that business.
        </p>
        <div className="legal-callout">
          <p>
            <strong>Please read carefully.</strong> These Terms include important
            limitations — in particular,{' '}
            <a href="#visualizations">how visualizations should be understood</a>,
            a <a href="#disclaimers">disclaimer of warranties</a>, a{' '}
            <a href="#liability">limitation of liability</a>, and an{' '}
            <a href="#disputes">agreement to resolve disputes by binding
            arbitration on an individual basis</a> (which you may opt out of).
          </p>
        </div>
      </>
    ),
  },
  {
    id: 'definitions',
    title: 'Definitions',
    body: (
      <ul>
        <li>
          <strong>“Customer”</strong> means a business that registers for or
          subscribes to Vizzion and embeds the widget on a website it controls.
        </li>
        <li>
          <strong>“End User”</strong> means a person who interacts with the widget
          on a Customer’s website (for example, by uploading a photo and entering
          an email).
        </li>
        <li>
          <strong>“User Content”</strong> means content you provide, including
          photos you upload and the selections you make.
        </li>
        <li>
          <strong>“Visualization”</strong> means an image generated by the Service
          that previews a product, material, or service applied to a photo.
        </li>
      </ul>
    ),
  },
  {
    id: 'service',
    title: 'The Service',
    body: (
      <p>
        Vizzion provides software that lets a Customer embed a widget on its
        website. An End User uploads a photo, selects options the Customer has
        configured, and the Service generates a Visualization that previews how a
        product or service might look. Where the Customer enables it, the End User
        provides an email address to receive or reveal the Visualization, and the
        Customer receives the submission as a lead. Vizzion provides the software
        only; it does not provide the products or services that Customers sell and
        is not a party to any transaction between a Customer and an End User.
      </p>
    ),
  },
  {
    id: 'eligibility',
    title: 'Eligibility and accounts',
    body: (
      <>
        <p>
          You must be at least {LEGAL.minimumAge} years old to use the Service.
          The Service is intended for business use by Customers and for personal,
          non-commercial use by End Users previewing a product or service.
        </p>
        <p>
          If you create an account, you must provide accurate information and keep
          it current. You are responsible for safeguarding access to your account
          and for all activity that occurs under it. Sign-in may use a one-time
          link sent to your email; keep that email secure. Notify us promptly at{' '}
          {supportEmailLink} if you suspect unauthorized use.
        </p>
      </>
    ),
  },
  {
    id: 'billing',
    title: 'Subscriptions, billing, and trials',
    body: (
      <>
        <p>
          Vizzion offers free and paid plans. The plans, features, usage limits,
          and current prices are described on our{' '}
          <a href={LEGAL.siteUrl + '/#pricing'}>pricing page</a>. By selecting a
          paid plan, you agree to the fees, billing period, and usage limits that
          apply to it.
        </p>
        <ul>
          <li>
            <strong>Subscription term and renewal.</strong> Paid plans are offered
            on a subscription basis (for example, monthly or annually) and renew
            automatically for successive periods of the same length unless
            cancelled before the renewal date.
          </li>
          <li>
            <strong>Free trials.</strong> We may offer a free trial on paid plans.
            Unless you cancel before the trial ends, the plan may convert to a
            paid subscription. Trial terms shown at sign-up control.
          </li>
          <li>
            <strong>Plan changes.</strong> You can request to upgrade, downgrade,
            or change plans by contacting {salesEmailLink}; changes are applied on
            a prorated basis. Usage above your plan’s limits may be subject to the
            overage settings you select or may pause certain features until the
            next cycle.
          </li>
          <li>
            <strong>Cancellation.</strong> You may cancel at any time. Cancellation
            stops future renewals; unless required by law, access continues until
            the end of the period you have already paid for.
          </li>
          <li>
            <strong>Taxes.</strong> Fees are exclusive of taxes, and you are
            responsible for any applicable taxes other than taxes on our income.
          </li>
          <li>
            <strong>Price changes.</strong> We may change prices or plan features.
            We will provide reasonable advance notice, and changes take effect on
            your next billing period.
          </li>
          <li>
            <strong>Refunds.</strong> Except where required by law or expressly
            stated in writing, fees are non-refundable, and there are no refunds
            or credits for partial periods or unused capacity.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: 'customer-obligations',
    title: 'Customer responsibilities (businesses using the widget)',
    body: (
      <>
        <p>If you are a Customer, you also agree that:</p>
        <ul>
          <li>
            <strong>You control your website and configuration.</strong> You are
            responsible for where you embed the widget, the domains you allow, the
            materials and options you configure, and your use of the leads and
            Visualizations you receive.
          </li>
          <li>
            <strong>You provide your own legal notices and consents.</strong> You
            will maintain your own privacy policy and obtain any notices,
            permissions, or consents required for collecting and using End-User
            information through the widget. As between you and Vizzion, you are the
            party responsible for that information (the controller or business),
            and Vizzion acts as your service provider or processor, as described in
            our <a href={LEGAL.siteUrl + '/privacy'}>Privacy Policy</a>. A data
            processing addendum is available on request at {legalEmailLink}.
          </li>
          <li>
            <strong>You will use leads lawfully.</strong> You will comply with all
            laws that apply to your outreach and marketing (for example, email and
            communications laws) and will honor End-User requests to access,
            correct, or delete their information.
          </li>
          <li>
            <strong>You will not misrepresent Visualizations.</strong> You will not
            present a Visualization as a photograph of a completed project, a
            guarantee of results, or a binding quote, and you will not remove or
            obscure any disclaimers.
          </li>
          <li>
            <strong>Brand assets.</strong> You grant Vizzion a limited license to
            use your name, logo, and brand assets solely to operate the Service for
            you (for example, branding the widget and result emails).
          </li>
        </ul>
      </>
    ),
  },
  {
    id: 'end-user-terms',
    title: 'Terms for End Users (people using a widget)',
    body: (
      <>
        <p>If you use a widget on a business’s website:</p>
        <ul>
          <li>
            You are interacting with that business, which is responsible for its
            products, services, pricing, and follow-up communications. Vizzion
            provides the visualization software only.
          </li>
          <li>
            You may upload a photo and provide an email address to receive a
            Visualization. Standard message and data rates may apply to any
            communications you receive.
          </li>
          <li>
            The business and Vizzion will handle your information as described in
            the business’s privacy notice and in our{' '}
            <a href={LEGAL.siteUrl + '/privacy'}>Privacy Policy</a>.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: 'content',
    title: 'Your content and the rights you grant',
    body: (
      <>
        <p>
          <strong>You keep ownership of your User Content.</strong> Uploading
          content does not transfer ownership to us.
        </p>
        <p>
          To operate the Service, you grant Vizzion and the Customer whose widget
          you used a worldwide, non-exclusive, royalty-free license to host,
          store, reproduce, modify (for example, to generate a Visualization),
          create derivative works from, and display your User Content and the
          resulting Visualization, in order to provide and improve the Service,
          communicate with you, and as otherwise described in our{' '}
          <a href={LEGAL.siteUrl + '/privacy'}>Privacy Policy</a>. This license
          ends when the content is deleted from our active systems, except for
          residual backup copies and as needed to comply with law or resolve
          disputes.
        </p>
        <p>When you submit User Content, you represent and warrant that:</p>
        <ul>
          <li>
            you have all rights and permissions necessary to submit it and to
            grant the license above;
          </li>
          <li>the content does not infringe or violate anyone’s rights;</li>
          <li>
            the content does not depict a person without that person’s consent
            (or, for a minor, the consent of a parent or legal guardian); and
          </li>
          <li>
            you are at least {LEGAL.minimumAge} years old, and any photo depicting
            a person is of an adult who has agreed.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: 'acceptable-use',
    title: 'Acceptable use',
    body: (
      <>
        <p>You agree not to, and not to allow anyone to:</p>
        <ul>
          <li>
            use the Service in violation of any law or to upload content you have
            no right to use;
          </li>
          <li>
            upload photos of other people or property without permission, or
            upload unlawful, infringing, hateful, harassing, or sexually
            exploitative content — uploading any sexual content involving a minor
            is strictly prohibited;
          </li>
          <li>
            upload malware, attempt to gain unauthorized access, probe or test the
            security of the Service, or interfere with its operation;
          </li>
          <li>
            scrape, copy, or harvest data; reverse engineer; or use the Service to
            build a competing product;
          </li>
          <li>
            circumvent usage limits, verification, or other technical protections;
            resell or sublicense the Service except as expressly permitted; or
          </li>
          <li>
            misrepresent a Visualization as a real, completed, or guaranteed
            result, or use the Service to deceive.
          </li>
        </ul>
        <p>
          We may investigate suspected violations and may remove content or
          suspend access to protect the Service and its users.
        </p>
      </>
    ),
  },
  {
    id: 'visualizations',
    title: 'Visualizations are illustrative previews',
    body: (
      <div className="legal-callout">
        <p>
          <strong>
            A Visualization is a digital approximation, not a real result.
          </strong>{' '}
          It is generated automatically from the photo you provide and the options
          you select to help you imagine a possible outcome.
        </p>
        <p>
          Visualizations are not exact and may differ from real-world results in
          color, texture, finish, scale, fit, materials, lighting, placement, and
          other respects. A Visualization is{' '}
          <strong>
            not a quote, estimate, recommendation, professional advice, or a
            guarantee
          </strong>{' '}
          that any product or service can be provided, installed, or will appear as
          shown. Differences between a Visualization and an actual result are
          expected and are not a defect in the Service. Always confirm details
          directly with the relevant business before making any decision or
          purchase.
        </p>
      </div>
    ),
  },
  {
    id: 'intellectual-property',
    title: 'Intellectual property and feedback',
    body: (
      <>
        <p>
          The Service, including its software, design, text, and trademarks (but
          excluding your User Content and a Customer’s own brand assets), is owned
          by Vizzion or its licensors and is protected by intellectual property
          laws. Subject to these Terms, we grant you a limited, non-exclusive,
          non-transferable, revocable license to use the Service for its intended
          purpose. You may not use our name or logos without permission, except to
          accurately refer to the Service.
        </p>
        <p>
          If you send us feedback or suggestions, you grant us a perpetual,
          irrevocable, royalty-free license to use them without restriction or
          obligation to you.
        </p>
      </>
    ),
  },
  {
    id: 'third-party',
    title: 'Third-party services',
    body: (
      <p>
        The Service relies on third-party providers (for example, hosting,
        storage, email delivery, image generation, and abuse prevention) and may
        link to or interoperate with third-party websites and services. We are not
        responsible for third-party services, and your use of them may be governed
        by their own terms and policies. The providers we use to process personal
        information are described in our{' '}
        <a href={LEGAL.siteUrl + '/privacy'}>Privacy Policy</a>.
      </p>
    ),
  },
  {
    id: 'dmca',
    title: 'Copyright and content complaints',
    body: (
      <>
        <p>
          We respect intellectual property rights. If you believe content on the
          Service infringes your copyright, send a notice to {legalEmailLink} that
          includes: (1) your signature; (2) identification of the copyrighted work;
          (3) identification of the allegedly infringing material and where it is
          located; (4) your contact information; (5) a statement that you have a
          good-faith belief the use is not authorized; and (6) a statement, under
          penalty of perjury, that your notice is accurate and that you are the
          owner or authorized to act on the owner’s behalf.
        </p>
        <p>
          We may remove allegedly infringing content and may terminate repeat
          infringers. If you believe your content was removed in error, you may
          submit a counter-notice using the same contact.
        </p>
      </>
    ),
  },
  {
    id: 'disclaimers',
    title: 'Disclaimers',
    body: (
      <p>
        THE SERVICE AND ALL VISUALIZATIONS ARE PROVIDED “AS IS” AND “AS AVAILABLE,”
        WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY,
        INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
        PURPOSE, TITLE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE
        WILL BE UNINTERRUPTED, SECURE, OR ERROR-FREE, OR THAT VISUALIZATIONS WILL
        BE ACCURATE, RELIABLE, OR REPRESENTATIVE OF ANY ACTUAL PRODUCT, SERVICE, OR
        RESULT. VIZZION IS NOT A PARTY TO, AND IS NOT RESPONSIBLE FOR, ANY
        TRANSACTION OR AGREEMENT BETWEEN A CUSTOMER AND AN END USER. SOME
        JURISDICTIONS DO NOT ALLOW CERTAIN DISCLAIMERS, SO SOME OF THE ABOVE MAY
        NOT APPLY TO YOU.
      </p>
    ),
  },
  {
    id: 'liability',
    title: 'Limitation of liability',
    body: (
      <p>
        TO THE FULLEST EXTENT PERMITTED BY LAW, VIZZION AND ITS AFFILIATES,
        OFFICERS, EMPLOYEES, AND SUPPLIERS WILL NOT BE LIABLE FOR ANY INDIRECT,
        INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, OR FOR
        ANY LOSS OF PROFITS, REVENUE, DATA, GOODWILL, OR BUSINESS, ARISING OUT OF
        OR RELATING TO THE SERVICE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
        DAMAGES. OUR TOTAL LIABILITY FOR ALL CLAIMS RELATING TO THE SERVICE WILL
        NOT EXCEED THE GREATER OF (A) THE AMOUNTS YOU PAID US IN THE TWELVE MONTHS
        BEFORE THE EVENT GIVING RISE TO THE CLAIM, OR (B) ONE HUNDRED U.S. DOLLARS
        (US$100). THESE LIMITATIONS APPLY EVEN IF A REMEDY FAILS OF ITS ESSENTIAL
        PURPOSE. SOME JURISDICTIONS DO NOT ALLOW CERTAIN LIMITATIONS, SO SOME OF
        THE ABOVE MAY NOT APPLY TO YOU.
      </p>
    ),
  },
  {
    id: 'indemnification',
    title: 'Indemnification',
    body: (
      <p>
        You will defend, indemnify, and hold harmless Vizzion and its affiliates
        from and against any claims, damages, liabilities, and expenses (including
        reasonable legal fees) arising out of or relating to your User Content,
        your use of the Service, your violation of these Terms or any law, or, if
        you are a Customer, your handling of End-User information and your products,
        services, and communications. We may assume the exclusive defense of any
        matter subject to indemnification, in which case you will cooperate with us.
      </p>
    ),
  },
  {
    id: 'termination',
    title: 'Suspension and termination',
    body: (
      <p>
        You may stop using the Service at any time. We may suspend or terminate
        your access, with or without notice, if you violate these Terms, if your
        use poses a risk to the Service or others, or as needed to comply with law.
        We may also discontinue the Service or any part of it. Upon termination,
        your right to use the Service ends; sections that by their nature should
        survive (including content licenses already granted, disclaimers,
        limitations of liability, indemnification, and dispute resolution) will
        survive.
      </p>
    ),
  },
  {
    id: 'changes',
    title: 'Changes to the Service and these Terms',
    body: (
      <p>
        We may modify the Service and these Terms from time to time. When we make
        material changes to these Terms, we will update the “Last updated” date at
        the top and, where appropriate, provide additional notice. Changes take
        effect when posted unless stated otherwise, and your continued use of the
        Service after that means you accept the revised Terms. If you do not agree,
        stop using the Service.
      </p>
    ),
  },
  {
    id: 'disputes',
    title: 'Governing law and dispute resolution',
    body: (
      <>
        <p>
          These Terms are governed by the laws of the State of{' '}
          {LEGAL.governingLawState}, United States, without regard to its
          conflict-of-laws rules, and by applicable U.S. federal law.
        </p>
        <h3>Informal resolution first</h3>
        <p>
          Before filing a claim, you agree to try to resolve the dispute informally
          by contacting us at {legalEmailLink}. If we cannot resolve it within 60
          days, either party may pursue the options below.
        </p>
        <h3>Binding individual arbitration</h3>
        <p>
          Except for the exceptions below, any dispute arising out of or relating
          to these Terms or the Service will be resolved by binding arbitration on
          an individual basis, administered by a recognized arbitration provider
          under its applicable rules. Arbitration will take place in the State of{' '}
          {LEGAL.governingLawState} or another mutually agreed location, and
          judgment on the award may be entered in any court of competent
          jurisdiction.
        </p>
        <div className="legal-callout">
          <p>
            <strong>Class-action and jury-trial waiver.</strong> Disputes will be
            conducted only on an individual basis and not as a class, collective,
            or representative action. You and Vizzion waive any right to a jury
            trial.
          </p>
        </div>
        <h3>Exceptions and opt-out</h3>
        <p>
          Either party may bring an individual claim in small-claims court or seek
          injunctive relief to protect intellectual property or stop misuse. You
          may opt out of arbitration by emailing {legalEmailLink} within{' '}
          {LEGAL.arbitrationOptOutDays} days of first accepting these Terms; if you
          opt out, disputes will be resolved in the state or federal courts located
          in the State of {LEGAL.governingLawState}, and you and Vizzion consent to
          their jurisdiction. To the extent a dispute proceeds in court rather than
          arbitration, those courts have exclusive jurisdiction and venue.
        </p>
      </>
    ),
  },
  {
    id: 'general',
    title: 'General terms',
    body: (
      <ul>
        <li>
          <strong>Entire agreement.</strong> These Terms and the documents they
          reference are the entire agreement between you and Vizzion regarding the
          Service and supersede prior agreements on that subject. A separate signed
          agreement with Vizzion, if any, controls where it conflicts with these
          Terms.
        </li>
        <li>
          <strong>Severability.</strong> If any provision is found unenforceable,
          the rest remains in effect.
        </li>
        <li>
          <strong>No waiver.</strong> Our failure to enforce a provision is not a
          waiver of it.
        </li>
        <li>
          <strong>Assignment.</strong> You may not assign these Terms without our
          consent; we may assign them in connection with a merger, acquisition, or
          sale of assets.
        </li>
        <li>
          <strong>Notices.</strong> We may provide notices to you by email, through
          the Service, or by posting them. You may send notices to us at{' '}
          {legalEmailLink}.
        </li>
        <li>
          <strong>Force majeure.</strong> We are not liable for delays or failures
          caused by events beyond our reasonable control.
        </li>
        <li>
          <strong>Export and sanctions.</strong> You will comply with applicable
          export-control and sanctions laws and will not use the Service if you are
          barred from doing so.
        </li>
      </ul>
    ),
  },
  {
    id: 'contact',
    title: 'Contact us',
    body: (
      <>
        <p>Questions about these Terms can be sent to:</p>
        <ul>
          <li>Email: {legalEmailLink}</li>
          {LEGAL.mailingAddress ? <li>Mail: {LEGAL.mailingAddress}</li> : null}
        </ul>
      </>
    ),
  },
];

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      intro={
        <p>
          These Terms govern your use of Vizzion — our website, our customer
          dashboard, and the embeddable visualization widget. They apply both to
          the businesses that subscribe to Vizzion and to the people who use a
          widget to preview a product or service. Please read them carefully.
        </p>
      }
      sections={sections}
    />
  );
}
